# Generated by Django 5.0.7 on 2024-07-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FEST', 'Festival'), ('CL', 'Cultural'), ('AD', 'Adventure')], default='FEST', max_length=5)),
            ],
        ),
    ]
